window.prelude = require 'prelude-ls'
require 'codemirror/mode/css/css'
require './src/engine.ls'
require './src/util.ls'
require './src/fft.js'
window.signals = require './src/signals.ls'
window.dsp = require './src/dsp.ls'
window.instruments = require './src/instruments.ls'
window.music = require './src/music.ls'
require './src/gui.jsx'
